fabric8-ui/ngx-login-client

- login.module.ts
- src/app/auth/authentication.service.ts
- src/app/user/user.service.ts
First step in refactoring the login client - removes the log routing logic (placing the onus on the consumer instead).
@pmuir @joshuawilson 
Next steps:
1) refactor user service to use observables
2) add httpclient which intercepts 401's or adds authorization header to requests when necessary
> feat(refactorauth): remove routing from auth service and dispatch events

- index.ts
- src/app/auth/authentication.service.ts
- src/app/shared/http.service.ts
- src/app/user/user.service.ts
Adds token when it's present and catches 401, 403 and 500's to handle
those appropriately instead of leaving it to the consumer
> feat(httpservice): adds http service to wrap all http calls

- src/app/user/user.service.ts
> fix(emptyuser): fixes creation logic for empty observable or cached user

- config/karma.conf.js
- config/webpack.test.js
- karma.conf.js
- src/app/auth/authentication.service.spec.ts
- src/app/user/user.service.spec.ts
Simple change to make sure we can run unit tests against the repo
Stubbed out starting points for two service tests, too
> fix(addtest): adds unit test configuration

- src/app/auth/authentication.service.ts
* the local storage cache wasn't working anyway
* federated tokens are now just refetched whenever the main token is refreshed
* add github token
> fix: use rxjs to publish federated tokens

- src/app/auth/authentication.service.ts
Calls /logout URL to clear session on backend
Fixes refresh to update more frequently (10 minutes or less)
Calls .next on refreshTokens to ensure UI is not blocked on 
initial login
> fix(logout): logs user out from keycloak

- src/app/auth/authentication.service.ts
Fixes #42 and https://github.com/fabric8io/fabric8-ui/issues/688
> fix(storage): store github/os tokens

- src/app/auth/authentication.service.ts
part 1 of 2 (corresponding change to platform coming)
> fix(logout): simplify logout behavior

- src/app/user/user.service.ts
Call the platform rest api to filter users by username:
https://github.com/almighty/almighty-core/commit/6fa69aca087dd92317900b556721cda559cd2aa0
fixes #48
> Avoid fetching all users for fetching users by username

- src/app/auth/authentication.service.ts
Broadcast noFederatedToken instead of authenticationError -- fixes #55.
> fix(AuthenticationService): Broadcast noFederatedToken

- src/app/user/profile.ts
Needed for profile pages in fabric8-ui.
Fixes issue #27
> fix(): Add company to profile

- index.ts
- src/app/auth/authentication.service.spec.ts
- src/app/auth/authentication.service.ts
- src/app/shared/realm-token.ts
Fixes https://github.com/fabric8-ui/ngx-login-client/issues/41
To be merged with fabric8-ui fix for https://github.com/fabric8io/fabric8-ui/issues/896
> fix(sso): hard-coded realm

- Jenkinsfile
- release.groovy
and add a build check to the PR step
> fix(build): update Jenkins to get the right code from the repo 

- src/app/auth/authentication.service.ts
as you suggested here is the PR
> fix(gihub.token): store github token for localhost flow

- src/app/shared/http.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/1316
> allow 401 if www-authenticate header present

- src/app/auth/authentication.service.ts
When running tests with protractor, protractor waits for all timeouts to be resolved.
At any given time, there is a timer for token refresh and so protractor waits indefinitely.
With this patch, protractor doesn't wait for token refresh timeout and hence it enables protractor
to run tests normally.
More info about angular zone and protractor - 
- https://medium.com/@TuiZ/you-may-need-protractor-for-more-than-testing-your-angular-4-app-e08533046e5d
- https://github.com/angular/protractor/blob/master/docs/timeouts.md#angular
> fix(RefreshTimer): Run refresh timer outside angular zone

- src/app/user/profile.ts
The user API now returns the user's cluster information too
https://auth.openshift.io/api/users/3383826c-51e4-401b-9ccd-b898f7e2397d
> feat(cluster): make user cluster aware

- src/app/user/profile.ts
Related to https://github.com/fabric8-ui/fabric8-ui/pull/2489
> fix(profile): added emailPrivate to profile

- src/app/shared/auth-api.ts
- src/app/shared/realm-token.ts
- src/app/shared/sso-api.ts
This is in preparation for a move to Angular 5
> fix(tokens): move to injection tokens

- src/app/auth/authentication.service.ts
This makes some cosmetic changes to code style, fixing some tslint issues.
> fix(authentication-service): fix tslint code style issues

- cico_setup.sh
run scl enable with exec to avoid creating new shell
> run scl enable with exec to avoid creating new shell

- cico_setup.sh
enable git  v2 for cico_release.sh
> fix(build): enable git v2 for cico_release.sh

- cico_setup.sh
fix(build): add git v2 location to PATH
> fix(build): add git v2 location to PATH
